/*
+--------------------------------------------------------------------------+
| PROJECT : PROTOCOL STACK                                                 |
| FILE    : p_mnss.h                                                       |
| SOURCE  : "sap\mnss.pdf"                                                 |
| LastModified : "2002-08-01"                                              |
| IdAndVersion : "6147.102.97.104"                                         |
| SrcFileTime  : "Thu Nov 29 09:48:44 2007"                                |
| Generated by CCDGEN_2.5.5A on Thu Sep 25 09:18:53 2014                   |
|           !!DO NOT MODIFY!!DO NOT MODIFY!!DO NOT MODIFY!!                |
+--------------------------------------------------------------------------+
*/

/* PRAGMAS
 * PREFIX                 : NONE
 * COMPATIBILITY_DEFINES  : NO (require PREFIX)
 * ALWAYS_ENUM_IN_VAL_FILE: NO
 * ENABLE_GROUP: NO
 * CAPITALIZE_TYPENAME: NO
 */


#ifndef P_MNSS_H
#define P_MNSS_H


#define CDG_ENTER__P_MNSS_H

#define CDG_ENTER__FILENAME _P_MNSS_H
#define CDG_ENTER__P_MNSS_H__FILE_TYPE CDGINC
#define CDG_ENTER__P_MNSS_H__LAST_MODIFIED _2002_08_01
#define CDG_ENTER__P_MNSS_H__ID_AND_VERSION _6147_102_97_104

#define CDG_ENTER__P_MNSS_H__SRC_FILE_TIME _Thu_Nov_29_09_48_44_2007

#include "CDG_ENTER.h"

#undef CDG_ENTER__P_MNSS_H

#undef CDG_ENTER__FILENAME


#include "p_mnss.val"

#ifndef __T_fac_inf__
#define __T_fac_inf__
/*
 * facility information
 * CCDGEN:WriteStruct_Count==2009
 */
typedef struct
{
  U16                       l_fac;                    /*<  0:  2> facility length                                    */
  U16                       o_fac;                    /*<  2:  2> facility offset                                    */
  U8                        fac[FACILITY_LEN];        /*<  4:251> facility content                                   */
  U8                        _align0;                  /*<255:  1> alignment                                          */
} T_fac_inf;
#endif

#ifndef __T_ss_ver__
#define __T_ss_ver__
/*
 * ss version
 * CCDGEN:WriteStruct_Count==2010
 */
typedef struct
{
  U8                        len;                      /*<  0:  1> length of ss version                               */
  U8                        ver[VERSION_LEN];         /*<  1:  8> ss version content                                 */
  U8                        _align0;                  /*<  9:  1> alignment                                          */
  U8                        _align1;                  /*< 10:  1> alignment                                          */
  U8                        _align2;                  /*< 11:  1> alignment                                          */
} T_ss_ver;
#endif


/*
 * End of substructure section, begin of primitive definition section
 */

#ifndef __T_MNSS_BEGIN_REQ__
#define __T_MNSS_BEGIN_REQ__
/*
 * 
 * CCDGEN:WriteStruct_Count==2011
 */
typedef struct
{
  U8                        ti;                       /*<  0:  1> Transaction Identifier                             */
  U8                        _align0;                  /*<  1:  1> alignment                                          */
  U8                        _align1;                  /*<  2:  1> alignment                                          */
  U8                        _align2;                  /*<  3:  1> alignment                                          */
  T_fac_inf                 fac_inf;                  /*<  4:256> facility information                               */
  T_ss_ver                  ss_ver;                   /*<260: 12> ss version                                         */
} T_MNSS_BEGIN_REQ;
#endif

#ifndef __T_MNSS_FACILITY_REQ__
#define __T_MNSS_FACILITY_REQ__
/*
 * 
 * CCDGEN:WriteStruct_Count==2012
 */
typedef struct
{
  U8                        ti;                       /*<  0:  1> Transaction Identifier                             */
  U8                        _align0;                  /*<  1:  1> alignment                                          */
  U8                        _align1;                  /*<  2:  1> alignment                                          */
  U8                        _align2;                  /*<  3:  1> alignment                                          */
  T_fac_inf                 fac_inf;                  /*<  4:256> facility information                               */
  T_ss_ver                  ss_ver;                   /*<260: 12> ss version                                         */
} T_MNSS_FACILITY_REQ;
#endif

#ifndef __T_MNSS_END_REQ__
#define __T_MNSS_END_REQ__
/*
 * 
 * CCDGEN:WriteStruct_Count==2013
 */
typedef struct
{
  U8                        ti;                       /*<  0:  1> Transaction Identifier                             */
  U8                        _align0;                  /*<  1:  1> alignment                                          */
  U8                        _align1;                  /*<  2:  1> alignment                                          */
  U8                        _align2;                  /*<  3:  1> alignment                                          */
  T_fac_inf                 fac_inf;                  /*<  4:256> facility information                               */
} T_MNSS_END_REQ;
#endif

#ifndef __T_MNSS_BEGIN_IND__
#define __T_MNSS_BEGIN_IND__
/*
 * 
 * CCDGEN:WriteStruct_Count==2014
 */
typedef struct
{
  U8                        ti;                       /*<  0:  1> Transaction Identifier                             */
  U8                        _align0;                  /*<  1:  1> alignment                                          */
  U8                        _align1;                  /*<  2:  1> alignment                                          */
  U8                        _align2;                  /*<  3:  1> alignment                                          */
  T_fac_inf                 fac_inf;                  /*<  4:256> facility information                               */
} T_MNSS_BEGIN_IND;
#endif

#ifndef __T_MNSS_FACILITY_IND__
#define __T_MNSS_FACILITY_IND__
/*
 * 
 * CCDGEN:WriteStruct_Count==2015
 */
typedef struct
{
  U8                        ti;                       /*<  0:  1> Transaction Identifier                             */
  U8                        _align0;                  /*<  1:  1> alignment                                          */
  U8                        _align1;                  /*<  2:  1> alignment                                          */
  U8                        _align2;                  /*<  3:  1> alignment                                          */
  T_fac_inf                 fac_inf;                  /*<  4:256> facility information                               */
} T_MNSS_FACILITY_IND;
#endif

#ifndef __T_MNSS_END_IND__
#define __T_MNSS_END_IND__
/*
 * 
 * CCDGEN:WriteStruct_Count==2016
 */
typedef struct
{
  U8                        ti;                       /*<  0:  1> Transaction Identifier                             */
  U8                        _align0;                  /*<  1:  1> alignment                                          */
  U16                       cause;                    /*<  2:  2> cause                                              */
  T_fac_inf                 fac_inf;                  /*<  4:256> facility information                               */
} T_MNSS_END_IND;
#endif


#include "CDG_LEAVE.h"


#endif
