CC=	arm-elf-gcc
LD=	arm-elf-ld

CFLAGS=	-O2 -fno-builtin -mthumb-interwork -mthumb
CPPFLAGS=-I. -I../../include -I../../include/condat -I../../gpf/inc \
	-I../../cdginc

OBJS=	dl_com.o dl_dcch0.o dl_dcch3.o dl_dph.o dl_drr.o dl_em.o dl_pei.o \
	dl_sacch0.o dl_signal.o dl_state.o dl_trace.o

all:	xipcode.o

xipcode.o:	${OBJS}
	${LD} -r -o $@ ${OBJS}

clean:
	rm -f *.[oa] *.out *errs
