/*
+--------------------------------------------------------------------------+
| PROJECT : PROTOCOL STACK                                                 |
| FILE    : p_app.h                                                        |
| SOURCE  : "sap\app.pdf"                                                  |
| LastModified : "2005-05-12"                                              |
| IdAndVersion : "NA.NA.00.2005"                                           |
| SrcFileTime  : "Thu Nov 29 09:30:08 2007"                                |
| Generated by CCDGEN_2.5.5A on Thu Sep 25 09:52:55 2014                   |
|           !!DO NOT MODIFY!!DO NOT MODIFY!!DO NOT MODIFY!!                |
+--------------------------------------------------------------------------+
*/

/* PRAGMAS
 * PREFIX                 : NONE
 * COMPATIBILITY_DEFINES  : NO (require PREFIX)
 * ALWAYS_ENUM_IN_VAL_FILE: NO
 * ENABLE_GROUP: NO
 * CAPITALIZE_TYPENAME: NO
 */


#ifndef P_APP_H
#define P_APP_H


#define CDG_ENTER__P_APP_H

#define CDG_ENTER__FILENAME _P_APP_H
#define CDG_ENTER__P_APP_H__FILE_TYPE CDGINC
#define CDG_ENTER__P_APP_H__LAST_MODIFIED _2005_05_12
#define CDG_ENTER__P_APP_H__ID_AND_VERSION _NA_NA_00_2005

#define CDG_ENTER__P_APP_H__SRC_FILE_TIME _Thu_Nov_29_09_30_08_2007

#include "CDG_ENTER.h"

#undef CDG_ENTER__P_APP_H

#undef CDG_ENTER__FILENAME


#include "p_app.val"


/*
 * End of substructure section, begin of primitive definition section
 */

#ifndef __T_APP_BAT_TEST_RSLT__
#define __T_APP_BAT_TEST_RSLT__
/*
 * 
 * CCDGEN:WriteStruct_Count==2883
 */
typedef struct
{
  U8                        test_rslt;                /*<  0:  1> test result                                        */
  U8                        _align0;                  /*<  1:  1> alignment                                          */
  U8                        _align1;                  /*<  2:  1> alignment                                          */
  U8                        _align2;                  /*<  3:  1> alignment                                          */
  U32                       additional_info;          /*<  4:  4> additional info                                    */
} T_APP_BAT_TEST_RSLT;
#endif


#include "CDG_LEAVE.h"


#endif
