/*
+--------------------------------------------------------------------------+
| PROJECT : PROTOCOL STACK                                                 |
| FILE    : p_ip.h                                                         |
| SOURCE  : "sap\ip.pdf"                                                   |
| LastModified : "2003-08-30"                                              |
| IdAndVersion : "8444.101.00.006"                                         |
| SrcFileTime  : "Thu Nov 29 09:43:40 2007"                                |
| Generated by CCDGEN_2.5.5A on Thu Sep 25 09:52:55 2014                   |
|           !!DO NOT MODIFY!!DO NOT MODIFY!!DO NOT MODIFY!!                |
+--------------------------------------------------------------------------+
*/

/* PRAGMAS
 * PREFIX                 : NONE
 * COMPATIBILITY_DEFINES  : NO (require PREFIX)
 * ALWAYS_ENUM_IN_VAL_FILE: NO
 * ENABLE_GROUP: NO
 * CAPITALIZE_TYPENAME: NO
 */


#ifndef P_IP_H
#define P_IP_H


#define CDG_ENTER__P_IP_H

#define CDG_ENTER__FILENAME _P_IP_H
#define CDG_ENTER__P_IP_H__FILE_TYPE CDGINC
#define CDG_ENTER__P_IP_H__LAST_MODIFIED _2003_08_30
#define CDG_ENTER__P_IP_H__ID_AND_VERSION _8444_101_00_006

#define CDG_ENTER__P_IP_H__SRC_FILE_TIME _Thu_Nov_29_09_43_40_2007

#include "CDG_ENTER.h"

#undef CDG_ENTER__P_IP_H

#undef CDG_ENTER__FILENAME


#include "p_ip.val"


/*
 * End of substructure section, begin of primitive definition section
 */

#ifndef __T_IP_ADDR_REQ__
#define __T_IP_ADDR_REQ__
/*
 * 
 * CCDGEN:WriteStruct_Count==1701
 */
typedef struct
{
  U32                       dst_addr;                 /*<  0:  4> destination address                                */
  U8                        trans_prot;               /*<  4:  1> transport protocol                                 */
  U8                        _align0;                  /*<  5:  1> alignment                                          */
  U8                        _align1;                  /*<  6:  1> alignment                                          */
  U8                        _align2;                  /*<  7:  1> alignment                                          */
} T_IP_ADDR_REQ;
#endif

#ifndef __T_IP_ADDR_CNF__
#define __T_IP_ADDR_CNF__
/*
 * 
 * CCDGEN:WriteStruct_Count==1702
 */
typedef struct
{
  U32                       src_addr;                 /*<  0:  4> source address                                     */
  U8                        err;                      /*<  4:  1> error code                                         */
  U8                        trans_prot;               /*<  5:  1> transport protocol                                 */
  U8                        _align0;                  /*<  6:  1> alignment                                          */
  U8                        _align1;                  /*<  7:  1> alignment                                          */
} T_IP_ADDR_CNF;
#endif


#include "CDG_LEAVE.h"


#endif
